version: "3.7"

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: "unless-stopped"
    networks:
      - gpt3-bingo

  backend:
    build:
      context: ./backend
      target: development-build-stage
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      MONGO_HOST: db
      MONGO_PORT: 27017
      MONGO_DATABASE: mongoose
    volumes:
      - ./backend:/app
      - /app/node_modules
    restart: "unless-stopped"
    networks:
      - gpt3-bingo
    links:
      - db
    depends_on:
      - db

  db:
    image: mvertes/alpine-mongo
    networks:
      - gpt3-bingo

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4001:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: "unless-stopped"

networks:
  gpt3-bingo:
    driver: bridge

volumes:
  data:
    driver: local
