version: "3.7"

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: "unless-stopped"
    networks:
      - gpt3-bingo

  backend:
    build:
      context: ./backend
      target: development-build-stage
      dockerfile: Dockerfile
    command: ["npm", "run", "debug"]
    ports:
      - 4000:3000
      - 9229:9229
    environment:
      MONGO_HOST: db
      MONGO_PORT: 27017
      MONGO_DATABASE: mongoose
      PORT: 3000
      # TS_NODE_PROJECT: ./tsconfig.json
    volumes:
      - ./backend/src:/app/src
      - ./backend/.env:/app/.env
      - ./backend/nodemon.json:/app/nodemon.json
      - ./backend/tsconfig.json:/app/dist/tsconfig.json
    restart: "unless-stopped"
    networks:
      - gpt3-bingo
    links:
      - db
    depends_on:
      - db

  db:
    image: mvertes/alpine-mongo
    networks:
      - gpt3-bingo
    ports:
      - "27017:27017"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4001:3000"
    volumes:
      - ./frontend/src:/app/src
    restart: "unless-stopped"

networks:
  gpt3-bingo:
    driver: bridge

volumes:
  data:
    driver: local
